
PROJECTNAME := deriving
OCAMLFIND := ocamlfind

NATDYNLINK :=YES

TYPECONV1 := \
  $(shell ${OCAMLFIND} query -p-format type_conv 2>/dev/null)
TYPECONV2 := \
  $(shell ${OCAMLFIND} query -p-format type-conv 2>/dev/null)

ifneq "${TYPECONV1}" ""
TYPECONVNAME := ${TYPECONV1}
else
ifneq "${TYPECONV2}" ""
TYPECONVNAME := ${TYPECONV2}
else 
TYPECONVNAME := 
endif
endif

TYPECONV := $(shell ${OCAMLFIND} query ${TYPECONVNAME} 2>/dev/null)

OBJEXT := .o
LIBEXT := .a
EXEEXT :=

